connection:
  jabber_id: "someone@pvp.net"
  resource: "xiff"
  # cert: "path/to/cert"
  # connect_timeout: 10
  password: "example_password"
  host: "chat.na1.lol.riotgames.com"
  port: "5223"
# 5222 TCP     XMPP client connection (RFC 3920)        Official
# 5223 TCP     XMPP client connection over SSL          Unofficial
# 5269 TCP     XMPP server connection (RFC 3920)        Official
# 5298 TCP UDP XMPP JEP-0174: Link-Local Messaging /    Official
#              XEP-0174: Serverless Messaging
# 8010 TCP     XMPP File transfers                      Unofficial